from __future__ import annotations

import io
import json
import tempfile
import unittest
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from unittest import mock

import cure as rf

from cure_subsequent_review.contracts import (
    EvidencePolicy,
    FindingProvenance,
    ModuleStatus,
    PriorFindingCandidate,
    PriorFindingLedger,
    PriorReviewCorpus,
    PriorReviewCorpusEntry,
    SubsequentReviewModule,
)
from cure_subsequent_review.control_plane import SubsequentReviewConfig, run_subsequent_review_intake
from cure_subsequent_review.decision import SubsequentReviewCommandMode, decide_subsequent_review
from cure_subsequent_review.finding_identity import reconcile_findings
from cure_subsequent_review.github_history import collect_pr_discussion
from cure_subsequent_review.prior_corpus import build_prior_review_corpus
from cure_subsequent_review.prior_findings import extract_prior_findings


CURE_FOOTER_BLOCK = (
    "<!-- CURE_REVIEW_FOOTER_START -->\n"
    "Generated by CURe for subsequent-review provenance.\n"
    "<!-- CURE_REVIEW_FOOTER_END -->"
)


@dataclass(frozen=True)
class PR:
    host: str = "github.com"
    owner: str = "example"
    repo: str = "demo"
    number: int = 9999


@dataclass(frozen=True)
class Session:
    session_id: str
    session_dir: Path
    review_md_path: Path
    created_at: str | None = None
    completed_at: str | None = None
    review_head_sha: str | None = None


class SubsequentReviewTestCase(unittest.TestCase):
    def setUp(self) -> None:
        rf._GH_API_SLURP_SUPPORTED = None

    def _extract_ledger_from_body(
        self,
        body: str,
        *,
        entry_id: str = "fixture:entry",
        source_type: str = "fixture",
        reviewed_head: str = "sha-fixture",
        artifact_path: Path | None = None,
    ) -> PriorFindingLedger:
        entry_kwargs: dict[str, Any] = {
            "entry_id": entry_id,
            "source_type": source_type,
            "provenance": {},
            "body": body,
            "reviewed_head": reviewed_head,
        }
        if artifact_path is not None:
            entry_kwargs["artifact_path"] = artifact_path
        return extract_prior_findings(
            corpus=PriorReviewCorpus(
                status=ModuleStatus.SUCCESS,
                entries=(PriorReviewCorpusEntry(**entry_kwargs),),
            )
        )

    def _finding_candidate(
        self,
        *,
        finding_id: str,
        title: str,
        entry_id: str = "session-a",
        severity: str = "medium",
        section: str = "Technical Assessment",
        evidence: str = "app.py:1",
        reviewed_head: str | None = None,
        supersedes: tuple[str, ...] = (),
    ) -> PriorFindingCandidate:
        head = reviewed_head or f"sha-{entry_id}"
        return PriorFindingCandidate(
            finding_id=finding_id,
            severity=severity,
            section=section,
            title=title,
            source_evidence_snippets=(evidence,),
            reviewed_head=head,
            provenance=FindingProvenance(
                corpus_entry_id=entry_id,
                source_type="session_review",
                artifact_path=f"/tmp/{entry_id}/review.md",
                reviewed_head=head,
            ),
            supersedes=supersedes,
        )

    def _new_pr_args(self, *, subsequent_review_disabled: bool = False) -> Any:
        args = [
            "pr",
            "https://github.com/acme/repo/pull/14",
            "--if-reviewed",
            "new",
            "--no-index",
            "--no-review",
        ]
        if subsequent_review_disabled:
            args.insert(5, "--no-subsequent-review")
        return rf.build_parser().parse_args(args)

    def _reviewflow_paths(self, root: Path) -> Any:
        return rf.ReviewflowPaths(sandbox_root=root / "sandboxes", cache_root=root / "cache")

    def _assert_error_meta_preserves_common_artifacts(
        self,
        *,
        meta: dict[str, Any],
        session_dir: Path,
        message: str,
    ) -> None:
        self.assertEqual(meta["status"], "error")
        self.assertIn(message, meta["error"]["message"])
        self.assertEqual(meta["paths"]["agent_desc"], str(session_dir / "agent_desc.txt"))
        self.assertEqual(meta["paths"]["pr_context"], str(session_dir / "work" / "pr_context.json"))
        self.assertTrue((session_dir / "agent_desc.txt").is_file())
        self.assertTrue((session_dir / "work" / "pr_context.json").is_file())
        self.assertIn("chunkhound", meta)

__all__ = [
    "Any",
    "CURE_FOOTER_BLOCK",
    "EvidencePolicy",
    "FindingProvenance",
    "ModuleStatus",
    "PR",
    "Path",
    "PriorFindingCandidate",
    "PriorFindingLedger",
    "PriorReviewCorpus",
    "PriorReviewCorpusEntry",
    "Session",
    "SubsequentReviewCommandMode",
    "SubsequentReviewConfig",
    "SubsequentReviewModule",
    "SubsequentReviewTestCase",
    "build_prior_review_corpus",
    "collect_pr_discussion",
    "decide_subsequent_review",
    "extract_prior_findings",
    "io",
    "json",
    "mock",
    "reconcile_findings",
    "rf",
    "run_subsequent_review_intake",
    "tempfile",
    "unittest",
]
